//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BookDb : DbContext
    {
        public BookDb()
            : base("name=BookDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietGioHang> ChiTietGioHangs { get; set; }
        public virtual DbSet<CTPhieu> CTPhieux { get; set; }
        public virtual DbSet<DanhMuc> DanhMucs { get; set; }
        public virtual DbSet<GioHang> GioHangs { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<NXB> NXBs { get; set; }
        public virtual DbSet<PhieuNhap> PhieuNhaps { get; set; }
        public virtual DbSet<Sach> Saches { get; set; }
        public virtual DbSet<SaveHistory> SaveHistories { get; set; }
        public virtual DbSet<TacGia> TacGias { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<TheLoai> TheLoais { get; set; }
        public virtual DbSet<ChiTietTK> ChiTietTKs { get; set; }
    
        public virtual ObjectResult<Sach> PTonKho()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sach>("PTonKho");
        }
    
        public virtual ObjectResult<Sach> PTonKho(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sach>("PTonKho", mergeOption);
        }
    
        public virtual ObjectResult<Sach> TimKiem(string strSearch, Nullable<int> sL)
        {
            var strSearchParameter = strSearch != null ?
                new ObjectParameter("StrSearch", strSearch) :
                new ObjectParameter("StrSearch", typeof(string));
    
            var sLParameter = sL.HasValue ?
                new ObjectParameter("SL", sL) :
                new ObjectParameter("SL", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sach>("TimKiem", strSearchParameter, sLParameter);
        }
    
        public virtual ObjectResult<Sach> TimKiem(string strSearch, Nullable<int> sL, MergeOption mergeOption)
        {
            var strSearchParameter = strSearch != null ?
                new ObjectParameter("StrSearch", strSearch) :
                new ObjectParameter("StrSearch", typeof(string));
    
            var sLParameter = sL.HasValue ?
                new ObjectParameter("SL", sL) :
                new ObjectParameter("SL", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sach>("TimKiem", mergeOption, strSearchParameter, sLParameter);
        }
    
        public virtual ObjectResult<string> TEST(string a)
        {
            var aParameter = a != null ?
                new ObjectParameter("A", a) :
                new ObjectParameter("A", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("TEST", aParameter);
        }
    
        public virtual ObjectResult<ChiTietDH_Result> ChiTietDH(string maGH)
        {
            var maGHParameter = maGH != null ?
                new ObjectParameter("MaGH", maGH) :
                new ObjectParameter("MaGH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChiTietDH_Result>("ChiTietDH", maGHParameter);
        }
    }
}
