//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietTK
    {
        public string MaTK { get; set; }
        public string TenTK { get; set; }
        public string TenHienThi { get; set; }
        public string MatKhau { get; set; }
        public string Email { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<byte> Quyen { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
