//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.ChiTietGioHangs = new HashSet<ChiTietGioHang>();
            this.CTPhieux = new HashSet<CTPhieu>();
        }
    
        public string MaSach { get; set; }
        public string TenSach { get; set; }
        public string MaTL { get; set; }
        public string MaNXB { get; set; }
        public string MaTG { get; set; }
        public Nullable<int> SL { get; set; }
        public Nullable<double> GiaTien { get; set; }
        public string Hinh { get; set; }
        public Nullable<int> UuTien { get; set; }
        public Nullable<int> MaDM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietGioHang> ChiTietGioHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPhieu> CTPhieux { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual NXB NXB { get; set; }
        public virtual TacGia TacGia { get; set; }
        public virtual TheLoai TheLoai { get; set; }
    }
}
