CREATE DATABASE BookManagement
Use BookManagement
CREATE TABLE KhachHang
(
	MaKH VARCHAR(10) PRIMARY KEY,
	TenKh NVARCHAR(10),
	SoDT VARCHAR(11),
	Email VARCHAR(20),
	DiaChi NVARCHAR(200)
)
CREATE TABLE NhanVien
(
	Manv VARCHAR(10) PRIMARY KEY,
	TenNV NVARCHAR(20),
	SoDT VARCHAR(11),
	Email VARCHAR(20),
	ChucVu NVARCHAR(20)
)

CREATE TABLE PhieuNhap
(
	MaPN VARCHAR(10) PRIMARY KEY,
	MaNCC VARCHAR(10),
	NgayNhap DATETIME DEFAULT GETDATE(),
	MaNV VARCHAR(10)
)

CREATE TABLE CTPhieu
(
	MaPN VARCHAR(10),
	MaSach VARCHAR(10),
	SL TINYINT,
	Mota NVARCHAR(200),
	PRIMARY KEY(MaPN,MaSach)
)

CREATE TABLE NhaCungCap
(
	MaNCC VARCHAR(10) PRIMARY KEY,
	TenNCC NVARCHAR(20),
	Diachi NVARCHAR(200),
	SoDT VARCHAR(11)
)

CREATE TABLE TaiKhoan
(
	MaTK VARCHAR(10) PRIMARY KEY,
	TenTK VARCHAR(20) UNIQUE NOT NULL,
	TenHienThi NVARCHAR(50),
	MatKhau VARCHAR(20),
	Email VARCHAR(50),
	Quyen TINYINT DEFAULT 0,
	MaKH VARCHAR(10)
)

CREATE TABLE ChiTietTK
(
	MaTK VARCHAR(10),
	TenTK VARCHAR(20) PRIMARY KEY,
	TenHienThi NVARCHAR(50),
	MatKhau VARCHAR(20),
	Email VARCHAR(50),
	HinhAnh VARCHAR(50),
	Quyen TINYINT
)

CREATE TABLE TacGia
(	
	MaTG VARCHAR(10) PRIMARY KEY,
	TenTG NVARCHAR(20),
	Email VARCHAR(20),
	SoDT VARCHAR(11)
)

CREATE TABLE NXB
(
	MaNXB VARCHAR(10) PRIMARY KEY,
	TenNXB NVARCHAR(20),
	Email VARCHAR(20)
)

CREATE TABLE TheLoai
(
	MaTL VARCHAR(10) PRIMARY KEY,
	TenTL NVARCHAR(20),
	Mota NVARCHAR(200)
)

CREATE TABLE Sach
(
	MaSach VARCHAR(10) PRIMARY KEY,
	TenSach NVARCHAR(100),
	MaTL VARCHAR(10),
	MaNXB VARCHAR(10),
	MaTG VARCHAR(10),
	SL int,
	GiaTien FLOAT,
	Hinh VARCHAR(50),
	UuTien INT NULL,
	MaDM int
)

CREATE TABLE DanhMuc
(
	MaDM INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TenDM NVARCHAR(50),
	MetaTitle VARCHAR(100) NULL
)
Create Table SaveHistory
(
	ID Int Identity(1,1) Primary Key,
	AuditCode Varchar(50),
	AuditDate Datetime,
	AuditItemID Varchar(100),
	Description Nvarchar (4000),
	EventID Varchar (50)
)
Create Table GioHang
(
	MaGH VARCHAR(10) PRIMARY KEY,
	MaKH VARCHAR(10),
	NgayDatHang DATETIME,
	TongTien FLOAT,
	TinhTrang BIT
)
Create Table ChiTietGioHang
(
	MaGH VARCHAR(10),
	MaSach VARCHAR(10),
	SoLuong INT,
	GiaTien FLOAT
	PRIMARY KEY(MAGH,MASACH)
)
ALTER TABLE PhieuNhap
ADD CONSTRAINT FK_PN_NV FOREIGN KEY(MaNV) REFERENCES NhanVien(MaNV)

ALTER TABLE PhieuNhap
ADD CONSTRAINT FK_PN_NCC FOREIGN KEY(MaNCC) REFERENCES NhaCungCap(MaNCC)

ALTER TABLE CTPhieu
ADD CONSTRAINT FK_CTP_PN FOREIGN KEY(MaPN) REFERENCES PhieuNhap(MaPN)

ALTER TABLE CTPhieu
ADD CONSTRAINT FK_CTP_Sach FOREIGN KEY(MaSach) REFERENCES Sach(MaSach)


ALTER TABLE Sach
ADD CONSTRAINT FK_Sach_TL FOREIGN KEY(MaTL) REFERENCES TheLoai(MaTL)

ALTER TABLE Sach
ADD CONSTRAINT FK_Sach_TG FOREIGN KEY(MaTG) REFERENCES TacGia(MaTG)

ALTER TABLE Sach
ADD CONSTRAINT FK_Sach_NXB FOREIGN KEY(MaNXB) REFERENCES NXB(MaNXB)

ALTER TABLE Sach
ADD CONSTRAINT FK_Sach_DanhMuc FOREIGN KEY(MaDM) REFERENCES DanhMuc(MaDM)

ALTER TABLE ChiTietGioHang
ADD CONSTRAINT FK_CTGH_GH FOREIGN KEY(MaGH) REFERENCES GioHang(MaGH)

ALTER TABLE ChiTietGioHang
ADD CONSTRAINT FK_CTGH_Sach FOREIGN KEY(MaSach) REFERENCES Sach(MaSach)

ALTER TABLE GioHang
ADD CONSTRAINT FK_CTGH_KH FOREIGN KEY(MaKH) REFERENCES KhachHang(MaKH)

ALTER TABLE ChiTietTK
ADD CONSTRAINT FK_TK_CTTK FOREIGN KEY(MaTK) REFERENCES TaiKhoan(MaTK)
ON DELETE CASCADE

--ALTER TABLE CTHD
--ADD CONSTRAINT FK_CTHD_Sach FOREIGN KEY(MaSach) REFERENCES Sach(MaSach)
--ALTER TABLE CTHD
--ADD CONSTRAINT FK_CTHD_HD FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD)
--ALTER TABLE HoaDon
--ADD CONSTRAINT FK_HD_KH FOREIGN KEY(MaKH) REFERENCES KhachHang(MaKH)
--CREATE TABLE HoaDon
--(
--	MaHD VARCHAR(10) PRIMARY KEY,
--	MaKH VARCHAR(10),
--	Ngay DATE DEFAULT GETDATE(),
--	TongTien FLOAT
--)

--CREATE TABLE CTHD
--(
--	MaHD VARCHAR(10),
--	MaSACH VARCHAR(10),
--	SL TINYINT,
--	KhuyenMai FLOAT,
--	DonGia FLOAT,
--	PRIMARY KEY(MaHD,MaSach)
--)